### ISSUE TITLE
Can the module used in browser

### ISSUE THREAD

**Issue by valaxy** [ben-ng/finite-automata#2]
I see the source code used CommonJS module standard which only useable in node.  
Can it change to AMD or UMD which can be used in browser without any compability issue?

**Comment by ben-ng** [comment]
This module will work anywhere, it has no io dependencies. CommonJS is absolutely usable in the browser and is very well supported: http://browserify.org

**Comment by valaxy** [comment]
Thanks a lot, it's really helpful.
